### PR TITLE
Revert to last stable release

### PR DESCRIPTION
**Pull request by hadess**
The snapshot was not working as well as it used to.

CC @wjt

### CODE REVIEW

**Comment by wjt** [comment]
The specific issue that rendered it unusable for me this weekend was that hitting F11 to fullscreen stopped the game from running smoothly, permanently: toggling back to windowed did not resolve the problem. Nor did launching it in fullscreen with `-f` help. Only leaving the window at its original size, unusably small on a 4K monitor, allowed the game to run at 60fps.

Unfortunately I see the same result with this PR. So don't merge it on my account! Other things that have changed since this worked well for me include:

- Switching to Wayland
- Switching to Pipewire

**Comment by hadess** [comment]
I have a desktop machine that's not super performant, with Intel integrated graphics, and a 3440x1440 display, and the current Blastem worked fine, with about 20 to 30% CPU usage. I use Pipewire and Wayland too. Can you check whether OpenGL is enabled in the Video menu? It should be enabled by default.

**Comment by wjt** [comment]
Yep, it is:

Capture d’écran de 2022-03-14 16-28-36

(I'm on a Dell XPS 13 9380 with intel integrated graphics, Mesa Intel® UHD Graphics 620 (WHL GT2) apparently.)

I can check some more permutations of OS versions etc.

**Comment by hadess** [comment]
> I can check some more permutations of OS versions etc.

Might be an idea, even running from a live CD should work. I'm using Fedora 35 right now. Whether or not that works, it might be worth installing the `.Debug` flatpak and trying sysprof. Can you confirm that it's chugging because it's using too much CPU?

You could also try it unsandboxed, by setting `LD_LIBRARY_PATH=` to the Flatpak app/lib directory and launching the binary. Would be a good way to check that the problem isn't with the sandboxing.

> (I'm on a Dell XPS 13 9380 with intel integrated graphics, Mesa Intel® UHD Graphics 620 (WHL GT2) apparently.)

`Mesa Intel® UHD Graphics 630 (CFL GT2)`...

**Comment by wjt** [comment]
The stable version works perfectly on my Fedora 35 machine so I blame something on the Endless OS side…

**Comment by hadess** [comment]
> The stable version works perfectly on my Fedora 35 machine so I blame something on the Endless OS side…

OK, let's close this then.

**Pull request closed without merging**
